- packages/docs/src/content/docs/guides/extend/command.md
> docs: autofill

- README.md
- package.json
- pnpm-lock.yaml
> feat: add README.md

- pnpm-lock.yaml
- src/components/IconsPage/index.tsx
- src/components/Post/index.astro
- src/pages/blog/index.astro
- src/pages/en-us/blog/index.astro
- src/pages/ja-jp/blog/index.astro
> fix: fix some problems of blog pages #43

- src/content/docs/en-us/guides/facade/range.md
- src/content/docs/en-us/guides/facade/register-function.md
- src/content/docs/en-us/guides/facade/websocket.md
- src/content/docs/en-us/guides/plugins/sheets/sheets-formula.md
- src/content/docs/guides/facade/range.md
- src/content/docs/guides/facade/register-function.md
- src/content/docs/guides/facade/websocket.md
- src/content/docs/guides/plugins/sheets/sheets-formula.md
- src/pages/playground.astro
> docs: add custom formula

- src/content/docs/en-us/guides/facade/range.md
- src/content/docs/en-us/guides/facade/websocket.md
- src/content/docs/guides/facade/range.md
- src/content/docs/guides/facade/websocket.md
> docs: websocket note, FUniver api

- src/content/docs/en-us/guides/facade/index.mdx
- src/content/docs/guides/facade/index.mdx
用 facade createUniverSheet 创建universheet 会报错，不仅仅公式这里，其他的依赖也会报错。先引导用户不要使用这个API
> docs: facade example

- src/content/docs/en-us/guides/troubleshooting.mdx
- src/content/docs/guides/troubleshooting.mdx
> docs(troubleshooting): update peerDependencies note

- generate-api.mjs
close dream-num/engineering#23
> feat: add source link on typedoc

- src/content/docs/en-us/guides/facade/event-handler.md
- src/content/docs/guides/facade/event-handler.md
close dream-num/engineering#22
> docs: add event handler

- src/content/docs/guides/customization/canvas.md
- src/content/docs/guides/facade/doc.md
- src/content/docs/zh-cn/guides/customization/canvas.md
- src/content/docs/zh-cn/guides/facade/doc.md
> docs(docs): append text

- package.json
- packages/api/package.json
- packages/community/package.json
- packages/community/src/content/docs/guides/quick-start/_components/UMDGenerator/index.tsx
- packages/pro/package.json
- packages/shared/package.json
close https://github.com/dream-num/univer/issues/2027
close https://github.com/dream-num/univer/discussions/2026
> fix: fix umd generator

- packages/community/src/content/docs/guides/configuration/cell-data.mdx
- packages/community/src/content/docs/guides/facade/sheet.mdx
- packages/community/src/content/docs/zh-cn/guides/configuration/cell-data.mdx
- packages/community/src/content/docs/zh-cn/guides/facade/sheet.mdx
> docs: cell config, facade range api

- pnpm-lock.yaml
- pro/guides/sheet/deployment/docker.en-US.mdx
- pro/guides/sheet/deployment/docker.zh-CN.mdx
https://github.com/dream-num/helm-chart-private/issues/17
> chore: update pro deployment document

- src/docs/guides/sheet/facade/sheet-api.en-US.mdx
- src/docs/guides/sheet/facade/sheet-api.zh-CN.mdx
> docs(facade): fix facade getValues

- .github/workflows/check-pr.yml
- src/docs/guides/sheet/tutorials/csv-import-plugin.en-US.mdx
- src/docs/guides/sheet/tutorials/csv-import-plugin.zh-CN.mdx
> docs: fix csv import plugin docs

- src/docs/guides/doc/features/core.en-US.mdx
- src/docs/guides/doc/features/core.zh-CN.mdx
- update univer doc document about new features
> feat: update univer doc document about new features

- src/docs/guides/sheet/features/pivot-table.en-US.mdx
- src/docs/guides/sheet/features/pivot-table.zh-CN.mdx
> fix(pivot): fix pivot table doc error

- src/docs/guides/sheet/features/pivot-table.en-US.mdx
- src/docs/guides/sheet/features/pivot-table.zh-CN.mdx
> fix(pivot): fix pivot table typing error

- src/docs/guides/general/advanced/custom-formula.en-US.mdx
- src/docs/guides/general/advanced/custom-formula.zh-CN.mdx
- src/docs/guides/sheet/tutorials/migrate-luckysheet.en-US.mdx
- src/docs/guides/sheet/tutorials/migrate-luckysheet.zh-CN.mdx
> docs: formula, migrate luckysheet

- src/docs/guides/sheet/facade/sheet-api.en-US.mdx
- src/docs/guides/sheet/facade/sheet-api.zh-CN.mdx
> docs(facade): add facade worksheet row column docs

- src/docs/guides/general/server/usip.en-US.mdx
- src/docs/guides/general/server/usip.zh-CN.mdx
> feat: update usip document

- src/docs/guides/sheet/getting-started/cell-data.en-US.mdx
- src/docs/guides/sheet/getting-started/cell-data.zh-CN.mdx
> docs: cell data custom description

- src/docs/guides/doc/features/core.en-US.mdx
- src/docs/guides/doc/features/core.zh-CN.mdx
- src/docs/guides/sheet/features/core.en-US.mdx
- src/docs/guides/sheet/features/core.zh-CN.mdx
> fix: fix dead links

- src/docs/guides/general/server/docker.en-US.mdx
- src/docs/guides/general/server/docker.zh-CN.mdx
- src/docs/guides/general/server/kubernetes.en-US.mdx
- src/docs/guides/general/server/kubernetes.zh-CN.mdx
should deploy after publish new version
> feat: add docker compose document

- src/docs/guides/sheet/getting-started/cell-data.en-US.mdx
- src/docs/guides/sheet/getting-started/cell-data.zh-CN.mdx
> docs(formula): formula id and f

- src/docs/blog/post/this-is-univer.en-US.mdx
- src/docs/blog/post/this-is-univer.zh-CN.mdx
> fix: fix broken links

- src/docs/guides/sheet/features/pivot-table.en-US.mdx
- src/docs/guides/sheet/features/pivot-table.zh-CN.mdx
- src/docs/guides/sheet/features/pivot-table/pivot-facade.en-US.mdx
- src/docs/guides/sheet/features/pivot-table/pivot-facade.zh-CN.mdx
close https://github.com/dream-num/univer/issues/3650
> fix(pivot): fix typo

- src/examples/sheets-uniscript/china-id-validation.ts
- src/examples/sheets-uniscript/data.ts
- src/examples/sheets-uniscript/draw-univer-logo.ts
> fix(uniscript): set row height force, add china id validation example

- src/docs/guides/sheet/facade/sheet-api.en-US.mdx
- src/docs/guides/sheet/facade/sheet-api.zh-CN.mdx
- src/docs/guides/sheet/features/core/default-style-CN.mdx
- src/docs/guides/sheet/features/core/default-style-US.mdx
- src/docs/guides/sheet/getting-started/workbook-data.en-US.mdx
- src/docs/guides/sheet/getting-started/workbook-data.zh-CN.mdx
- src/pages/guides/sheet/features/core/_meta.en-US.json
- src/pages/guides/sheet/features/core/_meta.zh-CN.json
- src/pages/guides/sheet/features/core/default-style.en-US.mdx
- src/pages/guides/sheet/features/core/default-style.zh-CN.mdx
> feat(sheet): add default style document

- src/docs/guides/sheet/facade/row-col.en-US.mdx
- src/docs/guides/sheet/facade/row-col.zh-CN.mdx
API https://github.com/dream-num/univer/pull/3693
> docs(sheet): add setRowCustom and setColumnCustom
